name: publish
on: [push]
jobs:
publish-hugo-drone-docker-image:
runs-on: rockylinux-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hugo-drone Docker image
run: |
       docker build . --tag ghcr.io/andrewbeaton/hugo-drone:latest
       docker run ghcr.io/andrewbeaton/hugo-drone:latest
